services:



  reactive_resume:
    image: ghcr.io/amruthpillai/reactive-resume:latest
    env_file:
      - resume.env

    volumes:
      - ./volumes/resume_data:/app/data

    restart: always
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:3000/api/health').then((r) => { if (!r.ok) process.exit(1); }).catch(() => process.exit(1));"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - resume
    labels:
      traefik.enable: true
      traefik.http.routers.resume.rule: Host(`resume.home.marcinszymanski.pl`)
      traefik.http.routers.resume.tls.certresolver: letsencrypt
      traefik.http.routers.resume.entrypoints: websecure
      traefik.http.routers.resume.tls: true
      traefik.docker.network: resume


networks:
  resume:
    name: resume
    enable_ipv6: true
    ipam:
      config:
      - subnet: 2a01:4b00:ad59:aa00:0:2:12::/112
